#spring:
 #   mvc:
  #    view:
   #     prefix: /WEB-INF/
    #    suffix: .jsp
#spring:
 # freemarker:
  #  suffix: .ftl
   # template-loader-path: /WEB-INF/
#spring:
 # thymeleaf:
  #  prefix: /WEB-INF/
   # suffix: .html
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: 123456
    type: com.mchange.v2.c3p0.ComboPooledDataSource
